version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana:
        image: kibana:6.4.0
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
    redis:
        image: redis
        ports:
            - '6379:6379'
    logstash:
        image: docker.elastic.co/logstash/logstash:6.4.0
        links:
            - elasticsearch
            - redis
        volumes:
            - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
        command: logstash -f /usr/share/logstash/config/logstash.conf
        depends_on:
            - elasticsearch
            - redis